name: Build HTML and EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pigframe
          pip install pyxel
          sudo apt install libsdl2-ttf-2.0-0

      - name: Copy and clean pigframe
        run: |
          cp -r $(python -c "import pigframe; import os; print(os.path.dirname(pigframe.__file__))") src/
          rm -rf src/pigframe/__pycache__
          rm -rf src/pigframe/examples
          rm -rf src/pigframe/tests

      - name: Build pyxapp
        run: |
          pyxel package src src/main.py

      - name: Build HTML version
        run: |
          pyxel app2html ./src.pyxapp

      - name: Build Windows EXE
        run: |
          pyxel app2exe ./src.pyxapp

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-version
          path: src.html

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-exe
          path: src.exe

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src.html
            src.exe
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}